#!/bin/bash

version=$(php artisan app:version)
gitbranch=$(git branch | grep \*)
filename="biblesupersearch_api_$version.zip"
filepath="../releases/api/$filename"

filename_nobi="biblesupersearch_api_${version}_nobibles.zip"
filepath_nobi="../releases/api/$filename_nobi"

filename_lite="biblesupersearch_api_${version}_lite.zip"
filepath_lite="../releases/api/$filename_lite"

# files to be deleted / excluded from the release 
delfiles=(
    pack
    install
    uninstall
    update
    .env.example-cli
    readme.md
    tests/Feature/test_spreadsheets/kjv_full.csv
    tests/Feature/test_spreadsheets/kjv_full.xlsx
    tests/Feature/test_spreadsheets/kjv_full.ods
)

echo ''
echo 'This script will pack the Bible SuperSearch API code for release'

# Check git status
gitstatus=$(git status --porcelain)

if [[ $gitstatus != '' ]]
then
    echo ''
    echo 'Please commit your changes before packing'
    echo 'Only committed changes will be packed'
    exit # comment out ONLY for debugging of this script.
fi

echo ''
echo Application Version:
echo "* $version"
echo ''
echo ''
read -p "Is this correct? (Y/n) " -n 1 -r
if [[ !($REPLY =~ ^[Yy]$) ]]
then
    echo ''
    exit
fi

echo ''
echo ''
echo Current git branch:
echo "$gitbranch"
echo ''
read -p "Is this correct? (Y/n) " -n 1 -r
if [[ !($REPLY =~ ^[Yy]$) ]]
then
    echo ''
    exit
fi

echo ''
echo ''
echo 'Running tests (phpunit)'
echo ''
php artisan test --parallel # comment out ONLY for debugging of this script.

code=$?

if [[ !($code = 0) ]]
then
    echo ''
    echo ''
    echo 'Attempting serial tests'
    echo '';
    php ./vendor/bin/phpunit 

    code=$?
fi

if [[ !($code = 0) ]]
then
    echo ''
    echo 'The tests found some errors'
    echo 'Please fix errors before continuing';
    exit
fi


echo ''
echo ''
echo Output Filename:
echo "* $filename"
echo ''
echo ''

read -p "Create the release? (Y/n) " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    # do dangerous stuff
    echo
    echo 'Clearing out Laravel cacheing'
    php artisan config:cache 
    php artisan optimize:clear

    echo ''
    echo 'Creating ZIP file'
    git archive -o $filepath HEAD

    echo 'Copying Composer dependencies to ZIP file'
    zip -r -q $filepath vendor/

    echo ''
    echo 'Deleting unwanted files / dirs:'

    # delete unwanted files from ZIP file
    for i in ${delfiles[@]}; do
        echo "    Deleting file:  ${i}"
        zip -d -q $filepath ${i}
    done    

    # delete unwanted dirs from ZIP file
    zip --delete -q $filepath 'public/js/bin/enyo/2.5.1.1/tools/minifier/*'

    echo ''
    echo "Success!  File created at $filepath"

    # Create 'no Bibles' version
    cp $filepath $filepath_nobi

    zip --delete -q $filepath_nobi 'bibles/modules/*.zip'
    #zip -r -q $filepath_nobi bibles/modules/readme.txt

    echo ''
    echo "Success!  File created at $filepath_nobi"

    # Create 'lite' version
    cp $filepath_nobi $filepath_lite

    # Selected public domain Bibles
    zip -r -q $filepath_lite 'bibles/modules/kjv.zip' #English KJV
    zip -r -q $filepath_lite 'bibles/modules/chinese_union_trad.zip'
    # Hindi - no public domain Bibles 
    zip -r -q $filepath_lite 'bibles/modules/sagradas.zip' #Spanish
    zip -r -q $filepath_lite 'bibles/modules/martin.zip' # French
    zip -r -q $filepath_lite 'bibles/modules/svd.zip' #Arabic Smith Van Dyke
    zip -r -q $filepath_lite 'bibles/modules/tr.zip'  #Greek TR
    zip -r -q $filepath_lite 'bibles/modules/he_modern.zip' #Hebrew

    echo ''
    echo "Success!  File created at $filepath_lite"

fi
